name: update-types

on:
  push:
    branches: [ main ]

jobs:
  update-types:
    strategy:
      matrix:
        node-version: [ 18.x ]
        step: ['publish']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run types build script
        run: |
          cd types
          yarn ${{ matrix.step }}
